// ===========================================
// DATABASE TYPES (Auto-generated by Supabase CLI)
// Run: npm run db:generate
// ===========================================

export type UserRole = 'fan' | 'creator' | 'admin';
export type SubscriptionStatus = 'active' | 'cancelled' | 'expired' | 'past_due';
export type PostType = 'free' | 'subscribers_only' | 'ppv';
export type MediaType = 'image' | 'video' | 'audio';
export type TransactionType = 'subscription' | 'ppv' | 'tip' | 'chat_credits' | 'payout' | 'refund';
export type TransactionStatus = 'pending' | 'completed' | 'failed' | 'refunded';
export type MessageType = 'text' | 'image' | 'video' | 'ppv' | 'tip';
export type PayoutStatus = 'pending' | 'processing' | 'completed' | 'failed';

// ===========================================
// CORE TYPES
// ===========================================

export interface Profile {
  id: string;
  username: string;
  display_name: string | null;
  email: string;
  avatar_url: string | null;
  role: UserRole;
  is_verified: boolean;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreatorProfile {
  id: string;
  user_id: string;
  bio: string | null;
  banner_url: string | null;
  location: string | null;
  website_url: string | null;
  twitter_url: string | null;
  instagram_url: string | null;
  is_accepting_messages: boolean;
  message_price: number;
  minimum_tip: number;
  ai_chat_enabled: boolean;
  ai_personality_id: string | null;
  ai_chat_price_per_message: number;
  subscriber_count: number;
  post_count: number;
  total_earnings: number;
  blocked_countries: string[];
  created_at: string;
  updated_at: string;
}

export interface SubscriptionTier {
  id: string;
  creator_id: string;
  name: string;
  description: string | null;
  price_monthly: number;
  price_3_month: number | null;
  price_yearly: number | null;
  benefits: string[];
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface Subscription {
  id: string;
  subscriber_id: string;
  creator_id: string;
  tier_id: string;
  status: SubscriptionStatus;
  price_paid: number;
  billing_period: string;
  started_at: string;
  current_period_start: string;
  current_period_end: string;
  cancelled_at: string | null;
  external_subscription_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface Post {
  id: string;
  creator_id: string;
  content: string | null;
  post_type: PostType;
  ppv_price: number | null;
  is_published: boolean;
  published_at: string;
  scheduled_for: string | null;
  like_count: number;
  comment_count: number;
  is_pinned: boolean;
  created_at: string;
  updated_at: string;
  // Joined data
  media?: PostMedia[];
  creator?: Profile & { creator_profile?: CreatorProfile };
  is_liked?: boolean;
  is_bookmarked?: boolean;
  has_access?: boolean;
}

export interface PostMedia {
  id: string;
  post_id: string;
  media_type: MediaType;
  url: string;
  thumbnail_url: string | null;
  width: number | null;
  height: number | null;
  duration_seconds: number | null;
  file_size_bytes: number | null;
  sort_order: number;
  created_at: string;
}

export interface Message {
  id: string;
  conversation_id: string;
  sender_id: string;
  message_type: MessageType;
  content: string | null;
  media_url: string | null;
  ppv_price: number | null;
  is_ppv_unlocked: boolean;
  tip_amount: number | null;
  is_read: boolean;
  is_from_ai: boolean;
  created_at: string;
}

export interface Conversation {
  id: string;
  participant_1: string;
  participant_2: string;
  last_message_at: string;
  last_message_preview: string | null;
  unread_count_1: number;
  unread_count_2: number;
  created_at: string;
  // Joined
  other_user?: Profile;
}

// ===========================================
// AI CHAT TYPES
// ===========================================

export interface AIPersonality {
  id: string;
  creator_id: string;
  name: string;
  age: number | null;
  backstory: string | null;
  location: string | null;
  personality_traits: string[];
  interests: string[];
  turn_ons: string[];
  turn_offs: string[];
  speaking_style: string | null;
  emoji_usage: 'none' | 'minimal' | 'moderate' | 'heavy';
  response_length: 'short' | 'medium' | 'long';
  custom_system_prompt: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface AIChatSession {
  id: string;
  user_id: string;
  creator_id: string;
  personality_id: string;
  is_active: boolean;
  total_messages: number;
  total_spent: number;
  memory_context: Record<string, any>;
  created_at: string;
  updated_at: string;
  // Joined
  personality?: AIPersonality;
  creator?: Profile;
}

export interface AIChatMessage {
  id: string;
  session_id: string;
  role: 'user' | 'assistant';
  content: string;
  credits_charged: number;
  created_at: string;
}

// ===========================================
// TRANSACTION TYPES
// ===========================================

export interface Transaction {
  id: string;
  user_id: string;
  creator_id: string | null;
  transaction_type: TransactionType;
  status: TransactionStatus;
  gross_amount: number;
  platform_fee: number;
  net_amount: number;
  subscription_id: string | null;
  post_id: string | null;
  message_id: string | null;
  external_transaction_id: string | null;
  description: string | null;
  metadata: Record<string, any>;
  created_at: string;
  completed_at: string | null;
}

export interface CreditBalance {
  id: string;
  user_id: string;
  balance: number;
  lifetime_purchased: number;
  lifetime_spent: number;
  updated_at: string;
}

// ===========================================
// API RESPONSE TYPES
// ===========================================

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  has_more: boolean;
}

// ===========================================
// FORM TYPES
// ===========================================

export interface CreatePostInput {
  content?: string;
  post_type: PostType;
  ppv_price?: number;
  scheduled_for?: string;
  media_files?: File[];
}

export interface UpdateProfileInput {
  display_name?: string;
  bio?: string;
  avatar?: File;
  banner?: File;
  location?: string;
  website_url?: string;
  twitter_url?: string;
  instagram_url?: string;
}

export interface AIPersonalityInput {
  name: string;
  age?: number;
  backstory?: string;
  location?: string;
  personality_traits: string[];
  interests: string[];
  turn_ons: string[];
  turn_offs?: string[];
  speaking_style?: string;
  emoji_usage: 'none' | 'minimal' | 'moderate' | 'heavy';
  response_length: 'short' | 'medium' | 'long';
  custom_system_prompt?: string;
}
